CC ?= gcc
AR ?= ar

CFLAGS += -fPIC -g

.PHONY: all

all: $(OUT_DIR)/libstb-image-resize.a

$(OUT_DIR)/stb_image_resize.o: src/stb_image_resize.c
	$(CC) $< -o $@ -c $(CFLAGS)

$(OUT_DIR)/libstb-image-resize.a: $(OUT_DIR)/stb_image_resize.o
	$(AR) rcs $@ $^
